# Generated by Django 2.2.4 on 2019-08-23 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insured',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_url', models.CharField(max_length=300)),
                ('policy_number', models.CharField(max_length=100)),
                ('zurich_policy_number', models.CharField(max_length=100)),
                ('assist_trip_id', models.IntegerField()),
                ('travel_assistance_voucher', models.CharField(max_length=100)),
                ('insurance_ticket', models.CharField(max_length=100)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Purchase')),
            ],
        ),
    ]
